//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePostsTutorial.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQWfIUN0iEobmSaDNEfI95MJ5_Z0Vgj8GjIsP15ojCxJcIo_3hsR8IGjhBVL_jaezuAKvIRrx8Xcr0wI8oda0UhjAn9NeELgW-NyDp1PVCcRJfNj0VVQFNmcGBZuvHLa9Q8O-D5tJdcechcHi44yFMy1UllRTjXInPBSZgxaL3HwKt-lsxfw3PAJ2JUa6aDuOEGYDd1SlZ3QcRprv3Vvw60PVVEJgXyZOmlC4Yov8OYFcKFkVvlM7XylAvwTiNcyWHRpebjx6Rf3srnyBWrGPLEPbrBJto4n4ZShIfkINVVqkWgovt368QDApMjs7OmMN-_ztTc2MpVDALCIc6TCGPvJJnt5yA")]
        public string LinkedinToken {
            get {
                return ((string)(this["LinkedinToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" #letshaveachat #motivation #mindfulness #motivationalquotes #quotes #mindset #in" +
            "spiration #goals #positivity #believe #success #inspirationalquotes #inspire #po" +
            "sitivevibes #love #life")]
        public string HashTags {
            get {
                return ((string)(this["HashTags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Have a lovely morning everyone")]
        public string Morning {
            get {
                return ((string)(this["Morning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Have a great afternoon all")]
        public string Noon {
            get {
                return ((string)(this["Noon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Have a great evening all")]
        public string Evening {
            get {
                return ((string)(this["Evening"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KZk_nGbskx")]
        public string LinkedinAuthor {
            get {
                return ((string)(this["LinkedinAuthor"]));
            }
        }
    }
}
